language: ruby
sudo: false
rvm:
- 2.1.0
before_script:
- npm install bower firebase-tools@^2.0
- "./node_modules/.bin/bower install"
script: bundle exec jekyll build
cache:
  directories:
  - node_modules
  - vendor/bundle
after_success:
- ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN"
env:
  global:
    secure: GA0VKk+fnzSlpA0Tqvk3eArzypahdQKqtYlbMhD4l4KIOkrobmS86j/MgPAytrEbMzWhMS5SODak0liFSG2eDslxDw6TZHGBZgYTAN1c+zr5613eVfU09n51VgXZvj7ziN773fx1zskuuWBRoxzNs8LGugPn8whdGPrR1pLcli0=
