language: ruby
rvm:
- 2.1.0
before_script:
- npm install bower firebase-tools@^2.0
- ./node_modules/.bin/bower install
script: bundle exec jekyll build
cache:
  directories:
    - node_modules
    - vendor/bundle
env:
  global:
    secure: DmqYFucaL5nu9MGopZd2CrqzIenOuarCpUqOD4bFV/ja+dOzC4mYi/85AWQxlDRHa+23WmsUSQ+k4G2KwISGndh39omlEHggadXR/2TS71sKucdr9wNmPYKAemolXD1QFgYJRqXHe0VF6dT4JGeZ6bYissmKO/lep8I99TQ5vXI=
after_success:
  - ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN
