language: ruby
sudo: false
rvm:
- 2.1.0
before_script:
- "./node_modules/.bin/bower install"
script: bundle exec jekyll build
cache:
  directories:
  - node_modules
  - vendor/bundle
deploy:
  provider: firebase
  edge:
    source: mbleigh/dpl
    branch: firebase
  on:
    all_branches: true
secure: "WF0AgZN36iUkf9iHheViF3gFRH7HlJ1MNuRdivXYSeK+nZTLVMzNJfbBoakGx8y2p3E78rROOf5GYlIxcxHtggTU5TXTZid5zj3o0SNAfxSJxwU3NCOcQiJ0skW4MBYg0T0STHtWjs7onKi/q0ykt+YnYIGaZA8Mua9f+AsciIc="
