language: ruby
sudo: false
rvm:
- '2.2'
before_script:
- npm install bower
- "./node_modules/.bin/bower install"
script: bundle exec jekyll build
cache:
  directories:
  - node_modules
  - vendor/bundle
deploy:
  provider: firebase
  skip_cleanup: true
  project:
    master: staticapps
  token:
    secure: s6Jp+xrJtPCSDpwEsOfPRqn+qroY35G8NP+LKXxJguKx0beCTgWEuvH7haNcMBSwr6JO8umtcNG9Z6aUdVqFphS5wJaQXUg6XdxfvlGKSRMO5RzVT0EAYnyci3rYUWponduSCSjgFZkXqhECuEadHqC+a1r4hr0qaznSDffk6Nw=
