language: ruby
sudo: false
rvm:
- 2.1.0
before_script:
- npm install bower
- "./node_modules/.bin/bower install"
script: bundle exec jekyll build
cache:
  directories:
  - node_modules
  - vendor/bundle
deploy:
  provider: firebase
  edge:
    source: mbleigh/dpl
    branch: firebase
  on:
    all_branches: true
env:
  global:
    secure: FM+qmB1wniRtEUDqdL6AqIacc5/qvgzffng89ReI3SPc4t2PqZoFF2LYXoWT2RRqwQ8HP/8c8z0SrRTFbTBP6PPyRLDLljaXf9EXTFh8BqLhQ28zhVCD5+8rbVlq3N09L9oP3ZDnvWjhtSF39nP/BECKw608/RJe803iHXdvM8M=
